title: NetSec Lab Notes
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

baseurl: "/my-labs"

url: https://fvasconc-netsec.github.io

aux_links:
  Linkedin: https://www.linkedin.com/in/fvt95/
